
package org.ewe;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AsyncSharcnetResponseImplService", targetNamespace = "http://ewe.org/", wsdlLocation = "file:/home/thiago/NetBeansProjects/WSAsharcnet/wsdl-backup/AsyncSharcnetJunto.wsdl")
public class AsyncSharcnetResponseImplService
    extends Service
{

    private final static URL ASYNCSHARCNETRESPONSEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.ewe.AsyncSharcnetResponseImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.ewe.AsyncSharcnetResponseImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/thiago/NetBeansProjects/WSAsharcnet/wsdl-backup/AsyncSharcnetJunto.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/thiago/NetBeansProjects/WSAsharcnet/wsdl-backup/AsyncSharcnetJunto.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ASYNCSHARCNETRESPONSEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public AsyncSharcnetResponseImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsyncSharcnetResponseImplService() {
        super(ASYNCSHARCNETRESPONSEIMPLSERVICE_WSDL_LOCATION, new QName("http://ewe.org/", "AsyncSharcnetResponseImplService"));
    }

    /**
     * 
     * @return
     *     returns AsyncSharcnetResponseImpl
     */
    @WebEndpoint(name = "AsyncSharcnetResponseImplPort")
    public AsyncSharcnetResponseImpl getAsyncSharcnetResponseImplPort() {
        return super.getPort(new QName("http://ewe.org/", "AsyncSharcnetResponseImplPort"), AsyncSharcnetResponseImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AsyncSharcnetResponseImpl
     */
    @WebEndpoint(name = "AsyncSharcnetResponseImplPort")
    public AsyncSharcnetResponseImpl getAsyncSharcnetResponseImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ewe.org/", "AsyncSharcnetResponseImplPort"), AsyncSharcnetResponseImpl.class, features);
    }

}
