
package org.ewe;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AsyncSharcnetResponseImpl", targetNamespace = "http://ewe.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.ewe.ObjectFactory.class,
    org.xmlsoap.schemas.ws._2004._08.addressing.ObjectFactory.class
})
public interface AsyncSharcnetResponseImpl {


    /**
     * 
     * @param relatesTo
     * @param parameters
     */
    @WebMethod
    @Oneway
    public void response(
        @WebParam(name = "RelatesTo", targetNamespace = "http://schemas.xmlsoap.org/ws/2004/08/addressing", header = true, partName = "RelatesTo")
        String relatesTo,
        @WebParam(name = "response", targetNamespace = "http://ewe.org/", partName = "parameters")
        Response parameters);

}
